### ISSUE TITLE
Lab 1-3

### ISSUE THREAD

**Issue by AlekseiMaslakov** [corradowaver/JavaLabs#1]
Здравствуйте

Lab1:
- a) Хотя бы if'ом нужно проверять
![image](https://user-images.githubusercontent.com/14160551/65875383-d717cb00-e38f-11e9-9af3-2b29fea43199.png)
- b) Не дружественный интерфейс, что вводить? Почему некоторые строки не вызывают никакого отклика? Пользователь посмотреть в код и понять, что происходит не может.
В реализации не учтено ограничение на случайный символ из задания.
- с) 
![image](https://user-images.githubusercontent.com/14160551/65875895-e51a1b80-e390-11e9-99bf-2cfe5c9a6f54.png)

Lab2:
Кажется это не весь вывод, который должен быть: 
![image](https://user-images.githubusercontent.com/14160551/65876155-4cd06680-e391-11e9-8680-8510f1ead44d.png)
Некоторые методы не использованы (как вы тогда проверяли их работу?) и зачем по коду множество ссылок на null? Дублирование кода в классе AnimalManager.

Lab3: Ok

**Comment by corradowaver** [comment]
Все исправлено, заnullуние убрал

**Comment by AlekseiMaslakov** [comment]
Здравствуйте
Lab1.a - ok
Lab1.b - ok
Lab1.c - ok
Lab2 - ok
Lab3 - ok
Lab4 - ok
